### ISSUE TITLE
Can the .NET Core Paketo Buildpack default to a specified port?

### ISSUE THREAD

**Issue by kvedurmu** [paketo-buildpacks/dotnet-core#4]
The resulting image of using the .NET Core CNB listens on port 80 (http) by default. Azure Spring Cloud was doing testing and mentioned this would fail, "as the default running user is not root." Let's switch it to 8080. 

**Notes**
- set default to 8080 when no port is specified

**Comment by ForestEckhardt** [comment]
@kvedurmu This is a request we have repeatedly denied because the buildpack at no point set a default port. Just like in every other buildpack .Net conf set a start command with $PORT as an option which allows the user to set the port by setting the $PORT environment variable of their apps running environment (as an example `docker run -e PORT=whatever-I-want`). IMO it isn't up to us set any default but it is up to the platform to do so.

**Comment by kvedurmu** [comment]
This seems reasonable. I'm going to close this out.
