### ISSUE TITLE
Investigate supporting .NET 6

### ISSUE THREAD

**Issue by fg-j** [paketo-buildpacks/dotnet-core#608]
.NET 6 was [recently released](https://devblogs.microsoft.com/dotnet/announcing-net-6/). ~A key new feature is native ARM64 support~ (Edit: A new feature is ARM64 support on macOS). Some questions to investigate:
- What would (and wouldn't) need to change in the language family buildpacks to support .NET 6?
- What is Microsoft's support agreement for .NET 6? Is this an LTS version?
- Is there demand for .NET 6 support in buildpacks?

**Comment by andi0b** [comment]
.NET 6 is the current LTS supported Version of .NET. The first LTS release since .NET Framework 4.8 and .NET Core 3.1

.NET 5 will be end of life on May 8, 2022. .NET Core 3.1 on December 3, 2022. 

**If .NET 6 is not going to be supported, this build pack should be archived and marked deprecated in the docs ASAP.**

If the build pack should have some future, #525 should be supported too. It is very common to start developing products on a preview SDK, if the release date is after the release date of the SDK.

**Comment by fg-j** [comment]
Thanks for that context @andi0b . Can you explain a bit more what you mean by

> It is very common to start developing products on a preview SDK, if the release date is after the release date of the SDK.

Specifically, "if the release date (of what?) is after the release date of the SDK."

**Comment by macsux** [comment]
I strongly agree with @andi0b comment - we should not be waiting for GA release before putting shovels in the ground and ideally releasing pre-releases of buildpacks for new versions coming down the pipe. ESPECIALLY since microsoft had a "go-live" policy attached to .NET 6 RC builds meaning customers could go to prod without waiting for GA and still be supported.

**Comment by fg-j** [comment]
Thanks @andi0b – your answer cleared up my confusion about .NET developers' process when it comes to preview releases. @andi0b and @macsux, your feedback is well taken.

@paketo-buildpacks/dependencies-maintainers would you be able to elaborate on what needs to be done in order to make the .NET 6 dependency available for buildpacks to consume? That's the first step in closing this issue.

**Comment by sophiewigmore** [comment]
@fg-j It looks like .NET Core 6.0.0 is[ already available](https://api.deps.paketo.io/v1/dependency?name=dotnet-runtime) (as well as SDK and ASPNET), as our automation picks up new version lines. Sometimes this fails if a new version line needs to be compiled in a different way, but this does not appear to be the case for .NET 6. 

To get it into the buildpack, we'd just need to add another [metadata dependency constraint](https://github.com/paketo-buildpacks/dotnet-core-runtime/blob/06e4bb12fb812616ee1e199975775c3df9683dad/buildpack.toml#L63-L66) for 6.0.* and then we can begin modifying buildpack behaviour as needed.

**Comment by fg-j** [comment]
I've started looking into this:

- [ ] https://github.com/paketo-buildpacks/dotnet-core-runtime/pull/277
- [ ] https://github.com/paketo-buildpacks/dotnet-core-sdk/pull/296
- [ ] https://github.com/paketo-buildpacks/dotnet-core-aspnet/pull/282

**Comment by ForestEckhardt** [comment]
With .Net Core version [`v0.10.0`](https://github.com/paketo-buildpacks/dotnet-core/releases/tag/v0.10.0) .Net 6 support has been added. Please test it out and feel free to open issues if you discover any problems!
