### ISSUE TITLE
Investigate: Syft SBOM support

### ISSUE THREAD

**Issue by sophiewigmore** [paketo-buildpacks/dotnet-core#712]
As of [Syft v0.46.0](https://github.com/anchore/syft/releases/tag/v0.46.0), .NET Core SBOM support is available, which we can leverage for SBOM support within the .NET Core buildpacks.

## Issue
This issue it to investigate the capabilities of the Syft SBOM support and understand what types of apps are supported. We'd like to understand if pre-compiled apps as well as source apps are supported. It would also be helpful to gather context on what file(s) Syft considers  so that we can determine if we should support SBOM creation in the `dotnet-publish` buildpack, and the `dotnet-execute` buildpack.

## Outcomes
For outcomes, we'd expect:
* context on this issue (or in the explorations repo) about what types of apps are supported, and what files/directories Syft looks at
* issues to be filed in the appropriate implementation buildpacks (`dotnet-publish`, `dotnet-execute`) about SBOM support. [An issue in `dotnet-publish`](https://github.com/paketo-buildpacks/dotnet-publish/issues/267) already exists, but we should modify it accordingly.
* If Syft doesn't support the full scope of apps we'd like SBOMs for, we should file an issue with Syft to do this and link it here/to related implementation buildpack issues

**Comment by ccheetham** [comment]
Spent a few days playing with using Syft to get SBOM details from .NET projects.  Most of what I include in this comment can be observed at this spike:

https://github.com/ccheetham/dotnet-sbom-spike

### syft args

The Syft command `syft packages` accepts a `SOURCE` arg which in the case of .NET can be a project directory or a project deps file.  Both of the following produce the same output (where `webapi-net50` is the project dir):
```
$ syft packages webapi-net50
$ syft packages webapi-net50/bin/Release/net5.0/publish/webapi-net50.deps.json
```

Actually, any path node between the project dir and dir containing the deps file seems to work.

### .NET framework support

Syft seems to work with `net6.0` and `net5.0` frameworks.  It does not work with `netcoreapp3.1`.

Worth noting that `net6.0` and `netcoreapp3.1` are LTS versions.

### getting SBOM info of runtimes

Since a deps file can be passed to Syft, Syft can generate output using the deps file of a locally installed framework installed from an SDK.  

```
$ syft packages $DOTNET_HOME/shared/Microsoft.AspNetCore.App/6.0.0/Microsoft.AspNetCore.App.deps.json
 ✔ Indexed .../shared/Microsoft.AspNetCore.App/6.0.0/Microsoft.AspNetCore.App.deps.json
 ✔ Cataloged packages      [1 packages]
NAME                                      VERSION  TYPE
Microsoft.AspNetCore.App.Runtime.osx-x64  6.0.0    dotnet
```

### self-contained apps

When Syft is run on a self-contained app, the output does include the runtime-specific entries but does not include the target platform itself.  However, the target platform can be gleaned from the app's deps file:

```
$ cat ... webapi-net60.deps.json | jq '.runtimeTarget.name'
".NETCoreApp,Version=v6.0"
$ cat ... webapi-net60-sc.deps.json | jq '.runtimeTarget.name'
".NETCoreApp,Version=v6.0/linux-x64"
```

**Comment by ForestEckhardt** [comment]
@ccheetham Thank you very much for you contribution to this investigation! Seeing that there is Syft SBOM support I have opened an issue to implement the layer style SBOM support in `dotnet-execute` which you can check out here https://github.com/paketo-buildpacks/dotnet-execute/issues/317. If you have any other comments feel free to comment on the issue in `dotnet-execute`!

I am going to close this issue out as the original investigation has drawn to a close and we have moved into implementation.
