### ISSUE TITLE
Alpine runtime to reduce final image size ?

### ISSUE THREAD

**Issue by clibequilibrium** [paketo-buildpacks/dotnet-core#848]
## Describe the Enhancement

Is it possible to tell this buildpack to use alpine base image from offical .NET core registry? for instance
``mcr.microsoft.com/dotnet/aspnet:7.0-alpine`` will use base image that will produce final built image of a simple C# app ~100 MB.

Current buildpack uses ubuntu 18 as base and installs some C libraries making the final image size around 200 MB.

## Motivation
I use this pack in serverless workflows and it is crucial to have the image size as small as possible for fast startups. 

Thank you.

![image](https://user-images.githubusercontent.com/105135724/211143762-23d49342-c009-4354-940a-fbea86c94cc3.png)

EDIT: small correction, the observed size was uncompressed. Compressed numbers are :

paketo buildpack: 93.28MB
alpine from dotnet:  45.06MB.  

Still 50% gain from just using alpine base

**Comment by sophiewigmore** [comment]
Hi @clibequilibrium, what builder/stack are you using, do you know? It would say it in the logs of your build.

The .NET Core buildpack is compatible with our Ubuntu 18.04 Full stack, which contains **many** libraries, but it's also compatible with our Base stack, which has less libraries. The .NET Core buildpack is not compatible with our Tiny stack, which contains the least number of packages, but we do have an [open issue](https://github.com/paketo-buildpacks/dotnet-core/issues/323) for that.

In order to use the alpine image, you'd need to create your own stack (we have documentation for that [here](https://paketo.io/docs/howto/create-custom-stack/#using-jam-create-stack)), which uses the alpine image. You can then use that stack in a builder (as[ outlined in the docs](https://paketo.io/docs/howto/create-custom-stack/#create-a-custom-builder-with-the-custom-stack)).

**Comment by clibequilibrium** [comment]
> Hi @clibequilibrium, what builder/stack are you using, do you know? It would say it in the logs of your build.
> 
> The .NET Core buildpack is compatible with our Ubuntu 18.04 Full stack, which contains **many** libraries, but it's also compatible with our Base stack, which has less libraries. The .NET Core buildpack is not compatible with our Tiny stack, which contains the least number of packages, but we do have an [open issue](https://github.com/paketo-buildpacks/dotnet-core/issues/323) for that.
> 
> In order to use the alpine image, you'd need to create your own stack (we have documentation for that [here](https://paketo.io/docs/howto/create-custom-stack/#using-jam-create-stack)) which will serve as the base image. You can then use that stack in a builder (as[ outlined in the docs](https://paketo.io/docs/howto/create-custom-stack/#create-a-custom-builder-with-the-custom-stack)) for your builds.

Thank you for your reply, I tried both base and full builders, but I guess runtime is determined by the actual stack base image. I will proceed with alpine as per docs you provided. Thank you for sending the references  !

Closing

**Comment by sophiewigmore** [comment]
Feel free to reach to us on Slack (paketobuildpacks.slack.com) if you have issues with stack creation.
